#pragma once

// All CSS custom properties resolved to literal hex values.
// No var() calls — required for Trident (IE engine) compatibility.
// R08: text-align kept only on <th> so md4c's per-cell align attribute is respected.
//
// Font sizes are ~2x the PRD baseline at user request. Segoe UI is first in
// the stack because Trident hints it best on Windows; the -apple-system /
// BlinkMacSystemFont aliases were removed because Trident treats them as
// unknown families and falls back unpredictably (cause of jittery text).
static const char kCSS[] =
    /* #15: max-width + margin:auto produced fractional pixel boundaries on
       every resize, which Trident rasters with subpixel jitter. Use a wrapper
       pattern: html paints the dark background, body is a fixed pixel grid
       centred via integer-pixel margins set at full-window widths the user
       will actually see. text-rendering and font smoothing hints below are
       no-ops on IE but harmless. */
    "html{background-color:#191919;}"
    "body{"
        "background-color:#191919;"
        "color:#E0E0E0;"
        "font-family:'Segoe UI',Tahoma,Verdana,Arial,sans-serif;"
        "font-size:32px;"
        "line-height:1.5;"
        "margin:48px 10%;"
        "padding:0;"
        "-ms-text-size-adjust:100%;"
        "-ms-high-contrast-adjust:none;"
    "}"
    "h1,h2,h3,h4,h5,h6{"
        "color:#FFFFFF;"
        "font-weight:600;"
        "margin-top:1.2em;"
        "margin-bottom:0.5em;"
        "line-height:1.25;"
    "}"
    "h1{font-size:2em;}"
    "h2{font-size:1.5em;}"
    "h3{font-size:1.25em;}"
    "h4{font-size:1.1em;}"
    "p{margin-bottom:1em;}"
    "a{color:#529CCA;text-decoration:none;}"
    "a:hover{text-decoration:underline;}"
    "code{"
        "background-color:#2D2D2D;"
        "border-radius:3px;"
        "padding:2px 6px;"
        "font-family:Consolas,'Courier New',monospace;"
        "font-size:0.92em;"
    "}"
    "pre{"
        "background-color:#1E1E1E;"
        "border:1px solid #333333;"
        "border-radius:6px;"
        "padding:18px;"
        "overflow-x:auto;"
        "font-family:Consolas,'Courier New',monospace;"
        "font-size:0.92em;"
        "line-height:1.45;"
    "}"
    "pre code{"
        "background-color:transparent;"
        "padding:0;"
        "border-radius:0;"
        "font-size:1em;"
    "}"
    "blockquote{"
        "border-left:4px solid #4A4A4A;"
        "margin-left:0;"
        "padding-left:18px;"
        "color:#9B9B9B;"
    "}"
    "table{"
        "border-collapse:collapse;"
        "width:100%;"
        "margin:1em 0;"
    "}"
    "th,td{"
        "border:1px solid #3A3A3A;"
        "padding:10px 14px;"
    "}"
    "th{"
        "background-color:#252525;"
        "color:#FFFFFF;"
        "font-weight:600;"
        "text-align:left;"
    "}"
    "ul,ol{"
        "padding-left:1.5em;"
        "margin-bottom:1em;"
    "}"
    "li{margin-bottom:0.25em;}"
    "hr{"
        "border:none;"
        "border-top:1px solid #333333;"
        "margin:2em 0;"
    "}"
    "img{"
        "max-width:100%;"
        "border-radius:4px;"
    "}"
    "del{color:#9B9B9B;}"
;
